return { nebula = {
    name                   = [[Nebula]],
    description            = [[Atmospheric Mothership]],
    acceleration           = 0.08,
    activateWhenBuilt      = true,
    airStrafe              = 0,
    autoheal               = 10,
    bankingAllowed         = false,
    brakeRate              = 0.96,
    builder                = false,
    buildPic               = [[nebula.png]],
    canFly                 = true,
    canGuard               = true,
    canMove                = true,
    canPatrol              = true,
    canSubmerge            = false,
    category               = [[GUNSHIP]],
    collide                = true,
    collisionVolumeOffsets = [[0 0 0]],
    collisionVolumeScales  = [[40 50 220]],
    collisionVolumeType    = [[box]],
    corpse                 = [[DEAD]],
    cruiseAltitude         = 370,

    customParams           = {
        cantuseairpads     = 1,
        modelradius        = [[40]],
        shield_emit_height = -100,

        outline_x    = 420,
        outline_y    = 420,
        outline_yoff = 40,
    },

    explodeAs              = [[LARGE_BUILDINGEX]],
    floater                = true,
    footprintX             = 5,
    footprintZ             = 5,
    health                 = 4900,
    hoverAttack            = true,
    iconType               = [[nebula]],
    metalCost              = 6000,
    noAutoFire             = false,
    noChaseCategory        = [[TERRAFORM FIXEDWING SATELLITE SUB]],
    objectName             = [[nebula.s3o]],
    script                 = [[nebula.lua]],
    selfDestructAs         = [[LARGE_BUILDINGEX]],
    sightDistance          = 1400,
    speed                  = 99,
    turnRate               = 200,
    upright                = true,
    workerTime             = 0,

    sfxtypes                = {
        explosiongenerators = {
            [[custom:brawlermuzzle]],
            [[custom:plasma_hit_96]],
            [[custom:EXP_MEDIUM_BUILDING_SMALL]],
        },
    },

    weapons = {
        {
            def                = [[CANNON]],
            mainDir            = [[0 1 0]],
            maxAngleDif        = 240,
            badTargetCategory  = [[FIXEDWING]],
            onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
        },
        {
            def                = [[CANNON]],
            mainDir            = [[0 -1 0]],
            maxAngleDif        = 240,
            badTargetCategory  = [[FIXEDWING]],
            onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
        },
        {
            def                = [[CANNON]],
            mainDir            = [[-1 0 0]],
            maxAngleDif        = 240,
            badTargetCategory  = [[FIXEDWING]],
            onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
        },
        {
            def                = [[CANNON]],
            mainDir            = [[1 0 0]],
            maxAngleDif        = 240,
            badTargetCategory  = [[FIXEDWING]],
            onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],
        },
        {
            def         = [[SHIELD]],
        },
    },

    weaponDefs = {
        CANNON = {
            name                    = [[Kinetic Driver]],
            alphaDecay              = 0.1,
            areaOfEffect            = 96,
            colormap                = [[1 0.95 0.4 1   1 0.95 0.4 1    0 0 0 0.01    1 0.7 0.2 1]],
            craterBoost             = 1,
            craterMult              = 0.5,

            customParams = {
                gatherradius        = [[90]],
                smoothradius        = [[60]],
                smoothmult          = [[0.08]],
                force_ignore_ground = [[1]],
                light_camera_height = 1500,
            },

            damage                  = { default = 45 },
            explosionGenerator      = [[custom:plasma_hit_32]],
            impulseBoost            = 30,
            impulseFactor           = 0.6,
            intensity               = 0.7,
            interceptedByShieldType = 1,
            noGap                   = false,
            noSelfDamage            = true,
            range                   = 680,
            reloadtime              = 0.4,
            rgbColor                = [[1 0.95 0.4]],
            separation              = 2,
            size                    = 2.5,
            sizeDecay               = 0,
            soundStart              = [[weapon/cannon/cannon_fire8]],
            soundHit                = [[explosion/ex_small14]],
            sprayAngle              = 360,
            stages                  = 12,
            tolerance               = 5000,
            turret                  = true,
            weaponType              = [[Cannon]],
            weaponVelocity          = 1500,
        },
        SHIELD = {
            name                    = [[Energy Shield]],
            damage                  = { default = 10 },
            customParams            = {
                unlinked              = true,
                shield_recharge_delay = 0,
            },
            exteriorShield          = true,
            shieldAlpha             = 0.1,
            shieldBadColor          = [[1 0.1 0.1 1]],
            shieldGoodColor         = [[0.1 0.1 1 1]],
            shieldInterceptType     = 3,
            shieldPower             = 10200,
            shieldPowerRegen        = 215,
            shieldPowerRegenEnergy  = 38,
            shieldRadius            = 675,
            smartShield             = true,
            visibleShield           = false,
            visibleShieldRepulse    = false,
            weaponType              = [[Shield]],
        },
    },

    featureDefs = {
        DEAD = {
            blocking = true,
            collisionVolumeOffsets  = [[0 0 0]],
            collisionVolumeScales   = [[40 50 220]],
            collisionVolumeType     = [[box]],
            featureDead             = [[HEAP]],
            footprintX              = 5,
            footprintZ              = 5,
            object                  = [[nebula_dead.s3o]],
        },
        HEAP = {
            blocking                = false,
            footprintX              = 4,
            footprintZ              = 4,
            object                  = [[debris4x4a.s3o]],
        },
    },
},
}
